---
- name: Django Application Hosting
  hosts: localhost
  become: true
  gather_facts: false
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

  roles:
    - django
